### ISSUE TITLE
Forked repository cannot make private

### ISSUE THREAD

**Issue by chibatching** [jmatsu/remocon-starter-kit#1]
In README, forking this repository is suggested.
But public forked repository can't make private. We have to [duplicate repository](https://help.github.com/articles/duplicating-a-repository/)

![image](https://user-images.githubusercontent.com/7804631/44129717-c2f33640-a084-11e8-8b00-26ba564fc214.png)

**Comment by jmatsu** [comment]
OMG ;(
Thank you for your report!

**Comment by jmatsu** [comment]
Updated. Thanks!
