### ISSUE TITLE
It might be a good to note that remote config api have to be enabled

### ISSUE THREAD

**Issue by chibatching** [jmatsu/remocon-starter-kit#3]
If the project was created before March 7, 2018, Remote Config API is not enabled. We should enable it on Cloud Console.
If not, retrieving access token command will fail with http 403 error.

https://firebase.google.com/docs/remote-config/use-config-rest?hl=en#get_started_using_the_rest_api

**Comment by jmatsu** [comment]
Indeed! 👀 
Let me add the link to the beginning of the preparation! Thank you so much 👍
